language: node_js

# Build only master, tags and PR's
# This prevents double builds on PRs (PR + branch build).
# https://github.com/travis-ci/travis-ci/issues/1147#issuecomment-441393807
if: type != push OR branch = master OR branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_script:
  - (cd ./test/certificates && ./generate.sh)

script:
  - npm run lint
  - npm test

matrix:
  include:
    - os: linux
      node_js: "lts/*"
      env: GYP_DEFINES="NODE_MBEDTLS_COVERAGE=1"
      after_success: codecov
    - os: linux
      node_js: "node"
    - os: windows
      node_js: "lts/*"
