language: node_js

matrix:
  include:
    - os: linux
      node_js: "lts/*"
      env: GYP_DEFINES="NODE_MBEDTLS_COVERAGE=1"
      after_success: codecov
    - os: linux
      node_js: "node"
    - os: windows
      node_js: "lts/*"
